spring.application.name=Email-OTP-Variation
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=enterYourEmail@gmail.com
spring.mail.password=yourAppPassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8082
